# Tạo file docker-compose.yml
services:
  # neo4j-loader:
  #   image: neo4j:5.24-enterprise
  #   entrypoint: ["/bin/bash", "/entrypoint.sh"]
  #   volumes:
  #     - neo4j-data:/data
  #     - neo4j-logs:/logs
  #     - neo4j-import:/import
  #     - neo4j-conf:/conf
  #     - ./backup:/backups
  #     - ./neo4j/entrypoint.sh:/entrypoint.sh
  #   depends_on:
  #     - neo4j
  neo4j:
    image: neo4j:5.24-enterprise
    container_name: healthcare-neo4j
    restart: always
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      # Cấu hình APOC qua biến môi trường
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/import
      - neo4j-conf:/conf
      - ./backup:/backups
    healthcheck:
      test:
        [
          "CMD",
          "cypher-shell",
          "-u",
          "${NEO4J_USERNAME}",
          "-p",
          "${NEO4J_PASSWORD}",
          "MATCH () RETURN count(*) as count",
        ]
      interval: 15s
      timeout: 15s
      retries: 10
      start_period: 60s
    networks:
      - healthcare-net

  fastapi:
    build: .
    container_name: healthcare-fastapi
    environment:
      - MODE=api
      - PORT=${API_PORT}
      - PYTHONPATH=/app
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./:/app
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - healthcare-net

  streamlit:
    build: .
    container_name: healthcare-streamlit
    environment:
      - MODE=ui
      - PYTHONPATH=/app
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    depends_on:
      neo4j:
        condition: service_healthy
    networks:
      - healthcare-net

  terminal:
    build: .
    container_name: healthcare-terminal
    environment:
      - MODE=cli
      - PYTHONPATH=/app
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
    volumes:
      - ./:/app
    depends_on:
      neo4j:
        condition: service_healthy
    tty: true
    stdin_open: true
    networks:
      - healthcare-net

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-conf:

networks:
  healthcare-net:
    driver: bridge
